### ISSUE TITLE
Ribbon customizations via User Custom Action

### ISSUE THREAD

**Issue by wobba** [rencoreab/customization-guide#1]
For simple actions where you display an icon with a URL using tokens this is still valid and the approach to use until extensions is available. So maybe a caution, and not avoid? Also... they will work in classic modes, where as extensions won't (I guess).

**Comment by waldekmastykarz** [comment]
Would it make sense to treat simple and complex Ribbon customizations separately or would an extended recommendation be a better approach?

**Comment by wobba** [comment]
caution: simple ribbon UI actions which point to a URL with tokens. When SPFx extensions are released and you do modern only, then a "don't"

complex ribbon actions: "don't", but wait for SPFx extensions in modern

**Comment by waldekmastykarz** [comment]
Makes sense. Wanna submit a PR? 😄

**Comment by waldekmastykarz** [comment]
Thanks @wobba!
