### ISSUE TITLE
Guidance on "when to use what"

### ISSUE THREAD

**Issue by thomasvochten** [rencoreab/customization-guide#11]
It would be nice to add some additional guidance on which techniques are best suited to achieve certain results, e.g "I want to add a custom action to individual items in a SharePoint list". This kind of information is already available in multiple places, but adding them here seems a good fit too. More of a suggestion than an actual issue of course...

**Comment by waldekmastykarz** [comment]
So if I understand correctly guidance from a scenario point of view rather than separate capabilities?

**Comment by thomasvochten** [comment]
Yes indeed - things like "If you want to brand your site, look at these techniques". Not sure that was the intention of this guide of course.

**Comment by waldekmastykarz** [comment]
The original idea behind what we currently have was to list the different customization capabilities and advise either for or against using them. Still, I think it would be indeed valuable to think about scenarios as well as they are more complicated and involve a number of capabilities some of which might work on their own but don't quite cooperate when used together. Do you have a couple of recommendations that we could begin with?

**Comment by waldekmastykarz** [comment]
@thomasvochten there is a similar guidance originally published by PnP available at https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/office-365-development-patterns-and-practices-solution-guidance. We're currently working on restructuring it and updating to reflect the latest capabilities in SharePoint and Office 365. Stay tuned for updates.

**Comment by thomasvochten** [comment]
Sounds good to me! Closing the issue.
