### ISSUE TITLE
Please update the SPFx Extensions part - it is out of preview already, should be probably moved to the "DO" part

### ISSUE THREAD

**Issue by PiotrekKrakowiak** [rencoreab/customization-guide#12]
Please update the SPFx Extensions part - it is out of preview already, should be probably moved to the "DO" part

**Comment by waldekmastykarz** [comment]
Good suggestion! Thank you and we will update it soon.

**Comment by PiotrekKrakowiak** [comment]
Thanks Waldek! And Kudos to you guys for a great article :-)
Cheers,
Piotrek

**Comment by waldekmastykarz** [comment]
It took a bit longer than expected but the changes are now live. Thank you once again for your feedback!

**Comment by PiotrekKrakowiak** [comment]
Thanks for the follow up Waldek!

Wesołych Świąt i dużo prezetów :-)

Cheers,
Piotrek

________________________________

**Comment by waldekmastykarz** [comment]
Dziękuję i wzajemnie wesołych świąt i szczęśliwego nowego roku!
