### ISSUE TITLE
Add column formatting using JSON to customize SharePoint

### ISSUE THREAD

**Issue by levesquesamuel** [rencoreab/customization-guide#13]
Whenever possible, column cuztomization should be done using column formating. If not possible due to 
technical limiations (e.g. call external JS) then use SPFx extension.

Your thoughts?

**Comment by waldekmastykarz** [comment]
That makes sense. If whatever you need to change about how the field is rendered using column formatting, you should use that. If it's insufficient for your needs, you could use SPFx field customizers instead.
