### ISSUE TITLE
Flow and LogicApps

### ISSUE THREAD

**Issue by wobba** [rencoreab/customization-guide#2]
For enterprise wide or larger workflow you might want to look at logicapps. A mention about this would be good.

**Comment by waldekmastykarz** [comment]
Good point and nice suggestion for including logic apps. Is there a clear threshold that you could use to determine when to stop using Flow and start considering Logic Apps or just a general scale recommendation? Also, how reliable are logic apps nowadays? Is there anything you have to take into account?

**Comment by wobba** [comment]
I think this page says it pretty well: https://docs.microsoft.com/en-us/azure/azure-functions/functions-compare-logic-apps-ms-flow-webjobs

Except, I think Flow works for larger solutions as well, running as a service account, as long as the Flow is shared so others can edit - meaning Flows where PowerUsers/Admins are expected to edit/change things.

**Comment by waldekmastykarz** [comment]
Nice one! The link is definitely something we should include. Care to submit a PR with the change? 😄

**Comment by waldekmastykarz** [comment]
Thanks @wobba!
