### ISSUE TITLE
Publishing and Comm sites

### ISSUE THREAD

**Issue by wobba** [rencoreab/customization-guide#3]
Maybe a mention about comm sites taking over for pub sites, but if you need full templating that is not ready - unless you develop something yourself at a higher cost.

**Comment by waldekmastykarz** [comment]
Communication sites definitely deserve a recommendation of their own. What would be yours: do, caution or avoid and why?

**Comment by wobba** [comment]
do - if you don't have high volume complex articles and many page layouts and need for targeting etc.
caution - see above, and then stick to publishing if you have to, or wait until comms is mature enough

**Comment by waldekmastykarz** [comment]
So a _caution_ which is a _do_ with a remark. How about support for publishing workflow (approval) and multilingual?

**Comment by wobba** [comment]
no - multilingual
no - approval, as Flow does not currently support minor/major version and checkin, but it's on the roadmap

**Comment by waldekmastykarz** [comment]
Check. Care for submitting a PR?

**Comment by waldekmastykarz** [comment]
Nice! Thanks!
